imports:
    - { resource: config.yml }

framework:
    test: ~
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: true

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: true

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
