composer_service_homepage:
    path: /
    defaults: { _controller: ayaline.controller.composer:indexAction }

composer_service_upload:
    path: /composer-service/upload
    defaults: { _controller: ayaline.controller.composer:uploadComposerAction }
    methods: [POST]
